# Generated by Django 4.1.2 on 2022-11-21 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_personal_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_firstname', models.CharField(max_length=20)),
                ('employee_lastname', models.CharField(max_length=20)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_designation', models.CharField(max_length=6)),
                ('employee_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('employee_category', models.CharField(choices=[('CV', 'Civilian'), ('Bip', 'Below IP'), ('Aip', 'IP&Above')], max_length=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_employed', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type_name', models.CharField(choices=[('Annual', 'Annual Leave'), ('Paternity', 'Paternity Leave'), ('Maternity', 'Maternity Leave')], max_length=30)),
                ('leave_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=150)),
                ('organisation_address', models.CharField(max_length=50)),
                ('organisation_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management_app.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10)),
                ('medical_certificate', models.BooleanField(default=False)),
                ('leave_application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_starting_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management_app.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management_app.leave_type')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management_app.organisation_branch'),
        ),
    ]
