# Generated by Django 4.1.2 on 2022-11-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='no_of_days_applied',
            field=models.IntegerField(default=30),
        ),
    ]
