# Generated by Django 4.1.2 on 2022-11-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_app', '0002_leave_application_no_of_days_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_type',
            old_name='leave_description',
            new_name='leave_type_description',
        ),
        migrations.AddField(
            model_name='leave_type',
            name='leave_max_duration',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management_app.leave_type')),
            ],
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management_app.leave'),
        ),
    ]
