# Generated by Django 4.1.2 on 2022-12-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_app', '0009_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
