# Generated by Django 4.1.2 on 2022-12-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_app', '0010_remove_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_employed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_designation',
            field=models.CharField(max_length=20),
        ),
    ]
