# Generated by Django 4.1.2 on 2022-12-30 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_app', '0011_alter_employee_date_employed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='remaining_leave_days',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_category',
            field=models.CharField(choices=[('Civilian', 'Civilian'), ('Below IP', 'Below IP'), ('IP&Above', 'IP&Above')], max_length=10),
        ),
    ]
